---
name: PR checks

"on":
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: false

env:
  SLACKREPO_IMAGE_NAME: aclemons/slackrepo
  # renovate: datasource=docker depName=aclemons/slackrepo
  SLACKREPO_IMAGE_VERSION: slack-15.0

jobs:
  changes:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      slackbuild_dirs: ${{ steps.set-output.outputs.slackbuild_dirs }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}

      - name: Get slackbuild directories which have changes.
        id: changed-dirs
        uses: tj-actions/changed-files@bb3376162b179308a79fc4450262a15a8e1d6888  # v37.0.4
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
          json: true
          quotepath: false

      - name: Get matrix output
        id: set-output
        run: |
          printf "slackbuild_dirs={\"dir\":${{ steps.changed-dirs.outputs.all_changed_files }}}\n" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-22.04
    if: ${{ needs.changes.outputs.slackbuilds_dirs != '' }}
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.slackbuild_dirs) }}
    needs: [changes]
    steps:
      - name: Set slackrepo docker image
        run: |
          printf 'DOCKER_IMAGE=%s:%s\n' "${{ env.SLACKREPO_IMAGE_NAME }}" "${{ env.SLACKREPO_IMAGE_VERSION }}" >> "$GITHUB_ENV"

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
        with:
          ref: ${{ github.head_ref }}

      - name: Build package
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}

          docker run --rm --cap-add SYS_ADMIN --entrypoint /bin/bash -v "$(pwd)":/var/lib/slackrepo/SBo/slackbuilds ${{ env.DOCKER_IMAGE }} -l -c "slackrepo build ${{ matrix.dir }}" 2>&1 | tee slackrepo-output || true

          printf '# %s - x86_64\n\n' > comment-output
          print '```\n' >> comment-output
          cat slackrepo-output >> comment-output
          print '```\n' >> comment-output

          rm slackrepo-output
        shell:
          bash

      - name: Comment with sbolint results
        uses: peter-evans/create-or-update-comment@c6c9a1a66007646a28c153e2a8580a5bad27bcfa  # v3.0.2
        with:
          issue-number: ${{ github.event.number }}
          body-path: sbolint-output
