---
name: Mirror Sync

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  codeberg:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          show-progress: false

      - name: Mirror to codeberg
        run: |
          git remote add mirror "https://${{ github.repository_owner }}:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/${{ github.repository }}.git"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
          git remote remove mirror
